Blog/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class AboutMeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Blog/Controllers/ContactController.cs
using Blog.Models;
using Blog.Models.ViewModels.Contacts;
using Blog.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactServices _contactServices;

        [TempData]
        public string Message { get; set; }

        public ContactController(IContactServices contactServices)
        {
            _contactServices = contactServices;
        }

        public IActionResult Index()
        {
            return View(new ContactViewModel
            {
                TempMessage = Message
            });
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactViewModel newContact)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(newContact);
                }
                var msg = await _contactServices.SaveContactAsync(newContact);
                TempData["message"] = msg;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Unable to access database.");
            }            
        }

        public async Task<IActionResult> List(string searchString)
        {
            try
            {
                var contacts = await _contactServices.GetContactListAsync(searchString);
                contacts.TempMessage = Message;
                return View(contacts);
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int contactId)
        {
            try
            {
                var msg = await _contactServices.DeleteContactAsync(contactId);
                TempData["message"] = msg;
                return RedirectToAction("List");
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }

    }
}

Blog/Controllers/PostsController.cs
using Blog.Models.ViewModels.Posts;
using Blog.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostServices _postServices;

        [TempData]
        public string Message { get; set; }

        public PostsController(IPostServices postServices)
        {
            _postServices = postServices;
        }
        public async Task<IActionResult> Index(string searchString, int? pageNumber)
        {
            try
            {   
                var posts = await _postServices.GetPaginatedPostsAsync(pageNumber, searchString);
                return View(new PostIndexViewModel
                {
                    Message = this.Message,
                    Posts = posts,
                    SearchString = searchString
                });
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }

        public async Task<IActionResult> Detail(int postId)
        {
            try
            {
                var post = await _postServices.GetPostViewModelAsync(postId);
                if (post == null)
                {
                    Message = "Post not found.";
                    return RedirectToAction("Index");
                }
                post.Message = this.Message;
                return View(post);
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }

        public async Task<IActionResult> Edit(int? postId)
        {
            try
            {   var id = postId ?? null;
                var post = await _postServices.GetPostViewModelAsync(id);
                return View(post);
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }

        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel post)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(post);
                }
                var msg = await _postServices.SavePostAsync(post);
                TempData["Message"] = msg;
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int postId)
        {
            try
            {
                var msg = await _postServices.DeletePostAsync(postId);
                TempData["message"] = msg;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Database Failure");
            }
        }
    }
}

Blog/Views/Shared/_DeleteModal.cshtml
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <form method="post">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

Blog/Views/Shared/_Layout.cshtml
@*@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="AboutMe" asp-action="Index">About</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Posts" asp-action="Index">Posts</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Contact" asp-action="Index">Contact</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Contact" asp-action="List">Contact List</a></li>                        
@*                    @if (SignInManager.IsSignedIn(User))
                    {
                    }
                    <partial name="_LoginPartial" />*@
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead" style="background-image: url(@ViewData["BackgroundImage"])">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="@ViewData["Page"]-heading">
                        <h1>@ViewData["Header"]</h1>
                        <span class="subheading">@ViewData["SubHeader"]</span>
                        <h2 class="subheading">@ViewData["PostSubHeader"]</h2>
                        <span class="meta">@ViewData["PostMeta"]</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main role="main" class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    @RenderBody()
                </div>
            </div>
        </div>            
    </main>
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>